### ISSUE TITLE
Release file has no extension 

### ISSUE THREAD

**Issue by minhhungit** [keva-dev/keva#108]
![image](https://user-images.githubusercontent.com/2279508/159385320-38c86611-a5d2-472f-98f0-a49e15a0c614.png)

**Comment by tuhuynh27** [comment]
Hi @minhhungit, that is binary file thus have no file extension, you have to run it on a linux/mac machine.
If you're using Windows, please pull the code and run `gradle build`, after that you can run `.jar` file built.
Currently we don't target Windows machines so we don't include `.exe` file for Windows, however feel free to create a pull request for that.

**Comment by minhhungit** [comment]
ah okay thanks, I thought it's something like zip file due to can open it using 7z 

![image](https://user-images.githubusercontent.com/2279508/159630873-a86bde3a-dd27-4504-905a-74f7dd4d066b.png)
