### ISSUE TITLE
Keva Proxy

### ISSUE THREAD

**Issue by haphananhtuan** [keva-dev/keva#119]
Instead of using our own implementation for proxy service, we are considering two open source libraries: [twenproxy](https://github.com/twitter/twemproxy) and [envoy](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/other_protocols/redis)

**Comment by tuhuynh27** [comment]
Hi @haphananhtuan, we can create a `markdown` file [here](https://github.com/keva-dev/blog)
