### ISSUE TITLE
Restructure the unit tests

### ISSUE THREAD

**Issue by tuhuynh27** [keva-dev/keva#126]
https://github.com/keva-dev/keva/blob/develop/core/src/test/java/dev/keva/core/server/AbstractServerTest.java Tests file is getting big (1000+ LOC), needs to restructure into many smaller test files

**Comment by tuhuynh27** [comment]
Is anyone interested in this issue? @axblueblader @ThanhChinhBK @yampml @taivtse

**Comment by hiepndd** [comment]
Hi @tuhuynh27, 
please assign it to me

**Comment by tuhuynh27** [comment]
Nice, thanks @hiepndd, if you need any guide or pair-programming, feel free to DM me via Slack

**Comment by taivtse** [comment]
Hi @hiepndd, are you working on this issue? I'm starting to work on it now. Please let me know when you are online.

**Comment by tuhuynh27** [comment]
Thanks @taivtse for picking up this, I think we can separate tests case by command group right?

Example: `TestStringCommands.java`, `TestHashCommands.java`
