### ISSUE TITLE
Better way to parse Long/Integer in our app?

### ISSUE THREAD

**Issue by tuhuynh27** [keva-dev/keva#127]
We're parsing Integer/Long like this:

```java
long afterInSeconds = Long.parseLong(new String(after, StandardCharsets.UTF_8));
```

Probably can find a better way to parse Long, we can add that code into `util` Gradle project, and simply replace all the old code.

**Comment by tuhuynh27** [comment]
Seems like @yampml will be interested on this issue right?

**Comment by yampml** [comment]
hmm, not sure is there other way rather than below, because resp protocol encoded bytes array is based on a string. I thought it was the same as Guava's Longs.toByteArray, but it's not :| 
```
    public static long bytesToLong(byte[] bytes) {
        long res = 0;
        for (int i = 0; i < bytes.length; i++) {
            res *= 10;
            res += bytes[i] - '0'; // throw NumberFormatException here if not a number. 
        }
        return res;
    }
```
