### ISSUE TITLE
Is there a slack channel for discussion?

### ISSUE THREAD

**Issue by the123saurav** [keva-dev/keva#58]
Hi guys, I just cloned the repo and has started consuming design docs and code.
Was just wondering what is the right channel to ask any doubts/clarifications before contributing?

**Comment by tuhuynh27** [comment]
Hi @the123saurav, if you have any doubt you can create Github Issue, we're very open to any discussion/questions.

**Comment by tuhuynh27** [comment]
Hi @the123saurav, I created a Slack workspace [here](https://join.slack.com/t/kevadev/shared_invite/zt-103vkwyki-pwum_qmcJgaOq6FIy3k2GQ), you can join now to have a better discussion experience.

Also guys @axblueblader @haphananhtuan @duongcongtoai @yampml, I've sent invitations to your @keva.dev email, please check also, thanks.

**Comment by the123saurav** [comment]
Thanks a lot for this! Would be much easy talking there.
